add tracing support with custom roundtripper
stoewer/go-nakadi pull request #81
Opened 2022-05-18 13:58 UTC by rdilruba

closes #80

2022-05-30 09:12 UTC, rdilruba commented
Would it be possible to get a review for this pr? 🙋‍♀️ @stoewer

2022-06-01 08:08 UTC, stoewer requested changes
Thank you for reporting #80 and this PR. The PR looks already quite good, but I still think there are some things that should be improved.

Since the tracer is already implemented as `http.RoundTripper` middleware, it would be good to use this as an opportunity to extend the `ClientOptions` such that also other middleware can be used. This would further decouple the tracing implementation from the rest of the client and allows users to create their own tracing or logging solutions. 

The changed API might look like this:

1. Add middleware to the `ClientOptions` in `nakadi.go`:
```go
// Middleware provides a chainable http.RoundTripper middleware that can be used
// to hook into requests e.g. for logging or tracing purposes.
type Middleware func(transport http.RoundTripper) http.RoundTripper

// ClientOptions contains all non mandatory parameters used to instantiate the Nakadi client.
type ClientOptions struct {
	TokenProvider     func() (string, error)
	ConnectionTimeout time.Duration
	Middleware        Middleware
}
```
2. Make the `Transport` from `helper.go` a `Middleware` and move it to its own file, for example `tracing.go`:
```go
type TracingOptions struct {
	...
}

type TracingMiddleware struct {
	tr http.RoundTripper
	...
}

func (t TracingMiddleware)  RoundTrip(req *http.Request) (*http.Response, error) {
	...
}

func NewTracingMiddleware(options *TracingOptions) Middleware {
	return func(trandport http.RoundTripper) http.RoundTripper {
		return TracingMiddleware{
			tr: trandport,
			...
		}
	}
}
```
3. Use the middleware in `newHTTPClient`

2022-06-02 17:07 UTC, rdilruba commented on helper.go
> +		Transport: &Transport{
Yes, that makes sense. I’ve removed tracing for streaming client.

2022-06-07 18:49 UTC, merged

2022-06-07 18:49 UTC, stoewer commented
Thank you for this contribution :+1: